### ISSUE TITLE
Замечания по заданию 1

### ISSUE THREAD

**Issue by ivan-uskov** [RomanKazantsev13/web-practice#1]
1) Зачем закоммитил var и vendor?
2) Лучше использовать routes.yaml, так нагляднее
3) Ошибки в тексте
```
Несмотря на это, я мне удается хорошо решать различные задачи
```
4) Ты перемудрил с ассетами, есть много лишних файлов, почему у тебя есть и просто css images папки, и папка assets? В этом задании можно было не использовать webpack, а сделать просто css файл. Но если ты решил применить webpack стоит прибраться в коде
5) Зачем столько подключенных модулей?

**Comment by RomanKazantsev13** [comment]
Замечания исправил. Но не совсем понял как надо правильно работать с ассетами, поэтому просто поместил папки css и images в папку public и удалил папку assets.

**Comment by ivan-uskov** [comment]
С ассетами можно прочитать тут `https://symfony.com/doc/current/frontend.html` расскажу об этом позже
